# Generated by Django 4.1.5 on 2023-01-31 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_post_is_public'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=64, verbose_name='ФИО')),
                ('specialist', models.CharField(max_length=64, verbose_name='Специальность')),
                ('image', models.ImageField(blank=True, null=True, upload_to='main/persons/', verbose_name='Изображение')),
                ('about', models.TextField(blank=True, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Личность',
                'verbose_name_plural': 'Лица',
            },
        ),
    ]
