# Generated by Django 4.1.5 on 2023-01-31 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_gallery_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='about',
            field=models.TextField(blank=True, null=True, verbose_name='О статье'),
        ),
    ]
